"""Shared constants for TDMS derived payload generation."""

SOURCE_SYSTEM = "TDMS_DERIVED"
AUTHORITY_LEVEL = "PROVISIONAL"
ARTIFACT_STATUS = "PARSED"

ARTIFACT_FILE = "artifact.json"
SHOT_META_FILE = "shot_meta.json"
SIGNAL_CATALOG_FILE = "signal_catalog.jsonl"
OPERATION_EVENTS_FILE = "operation_events.jsonl"
PROTECTION_EVENTS_FILE = "protection_events.jsonl"
WAVEFORM_REQUEST_FILE = "waveform_ingest_request.json"
WAVEFORM_BATCH_FILE = "waveform_channel_batch.jsonl"

DEFAULT_VALUE_TYPE = "DOUBLE"
DEFAULT_CHANNEL_SCOPE = "ALL"
DEFAULT_INGEST_MODE = "FULL"
WAVEFORM_BATCH_ENCODING = "raw"
WAVEFORM_BATCH_SAMPLE_SIZE = 4096

OPERATION_MODE_CODES = ("MANUAL", "AUTO", "REMOTE")
OPERATION_TASK_CODES = ("TASK_START", "TASK_RAMP", "TASK_STOP")
EXECUTION_STATUS_CODES = ("SUCCESS", "FAILED")
OPERATOR_IDS = ("AUTO", "OP_A", "OP_B")
COMMAND_NAMES = ("SETPOINT_CHANGE", "POWER_RAMP", "MANUAL_TWEAK")
COMMAND_TARGETS = ("HVPS", "RF", "GYROTRON")
COMMAND_GAIN_MIN = 0.5
COMMAND_GAIN_MAX = 2.0

PROTECTION_SCOPES = ("TUBE", "HVPS", "RF", "COOLING")
ACTION_TAKEN_CODES = ("TRIP", "SHUTDOWN", "ALARM", "NONE")
ACK_STATES = ("UNACKED", "ACKED")
ACTION_LATENCY_MIN_US = 50
ACTION_LATENCY_MAX_US = 50_000

PRIMARY_SOURCE_ROLE = "PRIMARY"
AUXILIARY_SOURCE_ROLE = "AUXILIARY"

TUBE_PROCESS_IDS = {
    "InPower": "ECRH:RF:IN_POWER",
    "RefPower": "ECRH:RF:REF_POWER",
    "NegVoltage": "ECRH:HVPS:NEG_VOLT",
    "NegCurrent": "ECRH:HVPS:NEG_CURRENT",
    "PosVoltage": "ECRH:HVPS:POS_VOLT",
    "PosCurrent": "ECRH:HVPS:POS_CURRENT",
    "FilaVoltage": "ECRH:GYROTRON:FILA_VOLT",
    "FilaCurrent": "ECRH:GYROTRON:FILA_CURRENT",
    "TiPumpCurrent": "ECRH:VACUUM:TI_PUMP_CURRENT",
}

PRIMARY_OPERATION_CHANNELS = (
    "NegVoltage",
    "PosVoltage",
    "FilaVoltage",
    "FilaCurrent",
    "InPower",
    "RefPower",
)
PRIMARY_PROTECTION_CHANNELS = (
    "NegVoltage",
    "NegCurrent",
    "PosVoltage",
    "PosCurrent",
    "InPower",
    "RefPower",
    "FilaCurrent",
    "TiPumpCurrent",
)
SHOT_REFERENCE_CHANNELS = ("NegVoltage", "PosVoltage", "InPower")

STEP_SMOOTH_WINDOW = 21
STEP_LEVEL_WINDOW = 200
STEP_PREPOST_WINDOW = 100
STEP_MERGE_GAP = 40
STEP_QUANTILE = 0.99
STEP_SIGMA_FACTOR = 1.5

RAMP_SMOOTH_WINDOW = 21
RAMP_SLOPE_WINDOW = 250
RAMP_MERGE_GAP = 120
RAMP_QUANTILE = 0.98
RAMP_SIGMA_FACTOR = 2.0
RAMP_MIN_DURATION_MS = 150.0

EDGE_GUARD_MS = 100.0
ACTIVE_WINDOW_COVERAGE_RATIO = 0.95
ACTIVE_SIGMA_FACTOR = 6.0
ACTIVE_PEAK_RATIO = 0.10

OPERATION_STEP_MIN_DELTA = {
    "NegVoltage": 0.0010,
    "PosVoltage": 0.0010,
    "FilaVoltage": 0.0030,
    "FilaCurrent": 0.0030,
    "InPower": 0.0300,
    "RefPower": 0.0200,
}
OPERATION_RAMP_MIN_DELTA = {
    "NegVoltage": 0.0020,
    "PosVoltage": 0.0020,
    "FilaVoltage": 0.0040,
    "FilaCurrent": 0.0040,
    "InPower": 0.0500,
    "RefPower": 0.0300,
}

EARLY_TERMINATION_TOLERANCE_RATIO = 0.02
EARLY_TERMINATION_TOLERANCE_SECONDS = 0.05
NO_WAVE_MIN_SIGNAL_LEVEL = 0.05
NO_WAVE_MIN_DYNAMIC_RANGE = 0.02
PEAK_HIGH_SIGMA_THRESHOLD = 10.0
PEAK_FILTER_WINDOW = 9

DROPOUT_FILTER_WINDOW = 11
DROPOUT_HIGH_RATIO = 0.85
DROPOUT_LOW_RATIO = 0.25
DROPOUT_WINDOW_MS = 100.0
DROPOUT_MIN_PLATEAU_MS = 20.0

COOLING_BASELINE_WINDOW_MS = 500.0
COOLING_SLOPE_WINDOW = 50
COOLING_CONTEXT_MS = 2_000.0
COOLING_SIGMA_FACTOR = 6.0
COOLING_MIN_DELTA = 0.04
COOLING_TOP_EVENTS = 5

EVENT_FAMILY_OPERATION = "OPERATION"
EVENT_FAMILY_PROTECTION = "PROTECTION"
EVENT_CODE_STEP = "OP_SETPOINT_STEP"
EVENT_CODE_RAMP = "OP_SETPOINT_RAMP"
EVENT_CODE_NO_WAVE = "PRX_NO_WAVE"
EVENT_CODE_EARLY_TERMINATION = "PRX_PULSE_EARLY_TERMINATION"
EVENT_CODE_PEAK_HIGH = "PRX_PEAK_ABS_HIGH"
EVENT_CODE_DROPOUT = "PRX_RAPID_DROPOUT"
EVENT_CODE_COOLING = "PRX_COOLING_ANOMALY"

SEVERITY_TRIP = "TRIP"
SEVERITY_WARN = "WARN"
